### ISSUE TITLE
Change how you detect mods that can be replaced by patcher

### ISSUE THREAD

**Issue by Alexdoru** [Sk1erLLC/Patcher#110] opened 2022-09-04 12:25 UTC
Since I use Patcher I have designed my mod to be 100% compatible with Patcher but this notification shows up on start up anyways and it's straigth up untrue and is missleading to users.

Imo you should print that message only for mods that you have listed here 
![image](https://user-images.githubusercontent.com/57050655/188313373-73bc6590-d05f-476d-bb11-8c91f71bd485.png)

![image](https://user-images.githubusercontent.com/57050655/188313311-7226dbd9-bc8b-4c12-b48c-ed6158ca5bfd.png)

**Comment by DJtheRedstoner** [comment] 2022-09-04 12:30
This is caused by a bug on our part. [This](https://github.com/Sk1erLLC/Patcher/blob/fa058363f81c524bf096b228d795629ca864f933/src/main/java/club/sk1er/patcher/Patcher.java#L400) should not be a contains checks.

**Comment by Sychic** [comment] 2022-09-15 16:57
Fixed in [1dcb1f9](https://github.com/Sk1erLLC/Patcher/commit/1dcb1f9ea48bbc8353eface4be7c21509a339dad)

**Closed by Sychic** 2022-09-15 16:57 UTC
