### ISSUE TITLE
Crash Conflict

### ISSUE THREAD

**Issue by 623667595** [Sk1erLLC/Patcher#162] opened 2023-10-11 06:48 UTC
[crash-2023-10-11_14.45.24-client.txt](https://github.com/Sk1erLLC/Patcher/files/12865833/crash-2023-10-11_14.45.24-client.txt)

**Comment by Sychic** [comment] 2024-03-16 03:02
Duplicate of #141

**Closed by Sychic** 2024-03-16 03:02 UTC
